### ISSUE TITLE
fix `yarn build`

### ISSUE THREAD

**Issue by soenkehahn** [TheToxProject/client#64]
Currently `yarn build` is broken on `master` (https://travis-ci.org/TheToxProject/client/builds/355266086).

(If the fix is not trivial and takes some time, I think the commits that broke `master` should be reverted.)

**Comment by SkyzohKey** [comment]
@soenkehahn Hey! Thanks for the report, just saw that I have merged the greenkeeper PR but it added webpack 4, and CRNA isn't yet compatible with Webpack 4 (this is being worked on), I'll revert the commit! :yum:

**Comment by SkyzohKey** [comment]
Fixed! :)
