### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by ilovelinux** [TheToxProject/client#99]
From the repository description:
> The Universal Tox client. Platform-agnostic Tox client with user-friendlyness in mind! http://beta.tox.chat 

From README.md:
> You can live preview most of the components on [The Storybook](https://tox-client.github.io/client)!

**Comment by SkyzohKey** [comment]
Oh, those will be fixes ASAP :)

**Comment by SkyzohKey** [comment]
Sorry for the delay, fixed! :)
